In [1]:
import pandas as pd
import numpy as np

from mlxtend.frequent_patterns import apriori, association_rules
from pyECLAT import ECLAT

<p style="background-image: linear-gradient(to right, #0aa98f, #68dab2)"> &nbsp; </p>

In [2]:
data = pd.read_csv('data/online_retail_II_clean.csv')
data.head(3)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
0,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
1,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50
2,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10

In [3]:
data_UK = data[data['Country']=='United Kingdom'][['Invoice', 'Description', 'Quantity']]
data_UK.head(3)

   Invoice                        Description  Quantity
0   536365                WHITE METAL LANTERN         6
1   536365  GLASS STAR FROSTED T-LIGHT HOLDER         6
2   536366             HAND WARMER UNION JACK         6

In [4]:
print(data_UK['Description'].str.contains('&').sum())
data_UK['Description'] = data_UK['Description'].str.replace('&', 'AND')

1485

<p style="background-image: linear-gradient(to right, #0aa98f, #68dab2)"> &nbsp; </p>

In [5]:
data_UK = data_UK.groupby(['Invoice', 'Description']).sum()
data_UK = data_UK.unstack(fill_value=0)

data_UK.columns = data_UK.columns.levels[1]
data_UK.reset_index(drop=True, inplace=True)
data_UK.sample(3)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 HANGING EGGS HAND PAINTED,...,ZINC HEARTS PLANT POT HOLDER,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
12417,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# data_UK = data_UK.map(lambda x: 0 if x==0 else 1)
data_UK = data_UK.map(lambda x: False if x==0 else True)
data_UK.sample(3)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 HANGING EGGS HAND PAINTED,...,ZINC HEARTS PLANT POT HOLDER,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
3213,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14241,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2972,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

<p style="background-image: linear-gradient(to right, #0aa98f, #68dab2)"> &nbsp; </p>

In [7]:
df_1 = apriori(data_UK, min_support=0.02, use_colnames=True)
# display(df_1)

df_2 = association_rules(df_1, metric='confidence') # min_threshold=0.7
display(df_2)

df_3 = association_rules(df_1, metric='lift', min_threshold=1)
display(df_3.nlargest(5, columns='lift'))

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.029845,0.037237,0.024249,0.8125,21.819921,0.023137,5.134738,0.983523

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
4,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.037237,0.029845,0.024249,0.651206,21.819921,0.023137,2.781456,0.991075
5,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.029845,0.037237,0.024249,0.812500,21.819921,0.023137,5.134738,0.983523
68,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.029845,0.040484,0.022522,0.754630,18.640382,0.021313,3.910482,0.975465
69,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.040484,0.029845,0.022522,0.556314,18.640382,0.021313,2.186581,0.986281
6,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.037237,0.040484,0.027979,0.751391,18.560395,0.026472,3.859547,0.982715

<p style="background-image: linear-gradient(to right, #0aa98f, #68dab2)"> &nbsp; </p>

In [8]:
columns = df_1.explode(column='itemsets')
columns['itemsets'].str.split(',')
print(data_UK.shape[1], columns.shape[0], columns['itemsets'].nunique())
columns = columns['itemsets'].unique()

2510 263 193

In [9]:
df = data_UK[[*columns]].copy()
df.tail(3)

Description,3 STRIPEY MICE FELTCRAFT,6 RIBBONS RUSTIC CHARM,60 CAKE CASES VINTAGE CHRISTMAS,60 TEATIME FAIRY CAKE CASES,72 SWEETHEART FAIRY CAKE CASES,ALARM CLOCK BAKELIKE GREEN,ALARM CLOCK BAKELIKE IVORY,ALARM CLOCK BAKELIKE PINK,ALARM CLOCK BAKELIKE RED,ANTIQUE SILVER T-LIGHT GLASS,...,WHITE SKULL HOT WATER BOTTLE,WOOD 2 DRAWER CABINET WHITE FINISH,WOODEN BOX OF DOMINOES,WOODEN HEART CHRISTMAS SCANDINAVIAN,WOODEN PICTURE FRAME WHITE FINISH,WOODEN SCHOOL COLOURING SET,WOODEN STAR CHRISTMAS SCANDINAVIAN,WOODLAND CHARLOTTE BAG,YOU'RE CONFUSING ME METAL SIGN,ZINC METAL HEART DECORATION
14472,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14473,False,False,False,False,False,True,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
14474,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df = df.apply(lambda col: [col.name if val else np.nan for val in col])
df.columns = np.arange(df.shape[1])
display(df.tail(3))

,0,1,2,3,4,5,6,7,8,9,...,183,184,185,186,187,188,189,190,191,192
14472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14473,NaN,NaN,NaN,NaN,NaN,ALARM CLOCK BAKELIKE GREEN,NaN,NaN,ALARM CLOCK BAKELIKE RED,ANTIQUE SILVER T-LIGHT GLASS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
eclat = ECLAT(df, verbose=True)
eclat.df_bin.tail(3)

100%|█████████████████████████████████████████████| 193/193 [00:17<00:00, 11.31it/s]
100%|███████████████████████████████████████████| 193/193 [00:00<00:00, 3045.59it/s]
100%|███████████████████████████████████████████| 193/193 [00:00<00:00, 2934.03it/s]

,JUMBO BAG OWLS,RABBIT NIGHT LIGHT,BOX OF 6 MINI 50'S CRACKERS,TRADITIONAL KNITTING NANCY,PAPER BUNTING RETROSPOT,PANTRY MAGNETIC SHOPPING LIST,PAPER CHAIN KIT 50'S CHRISTMAS,SPOTTY BUNTING,CREAM HEART CARD HOLDER,LADIES AND GENTLEMEN METAL SIGN,...,PACK OF 72 SKULL CAKE CASES,JUMBO SHOPPER VINTAGE RED PAISLEY,PAPER CHAIN KIT VINTAGE CHRISTMAS,PACK OF 60 PINK PAISLEY CAKE CASES,WOODEN BOX OF DOMINOES,GIN + TONIC DIET METAL SIGN,FELTCRAFT BUTTERFLY HEARTS,PAPER CHAIN KIT EMPIRE,BLUE STRIPE CERAMIC DRAWER KNOB,FELTCRAFT PRINCESS LOLA DOLL
14472,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14473,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
_1 = min_product = 1
_2 = max_product = 2     # eclat.df_bin.sum(axis=1).max() # DO NOT TRY
_3 = min_support = 0.02

a, b = eclat.fit(min_combination=_1, max_combination=_2, min_support=_3, verbose=True)
display(pd.Series(b).to_frame())

Combination 1 by 1

193it [00:11, 16.71it/s]

Combination 2 by 2

18528it [09:11, 33.62it/s]

                                                           0
JUMBO BAG OWLS                                      0.020104
RABBIT NIGHT LIGHT                                  0.031503
BOX OF 6 MINI 50'S CRACKERS                         0.020449
TRADITIONAL KNITTING NANCY                          0.030052
PAPER BUNTING RETROSPOT                             0.027772
...                                                      ...
LUNCH BAG  BLACK SKULL. & LUNCH BAG PINK POLKADOT   0.029085
LUNCH BAG CARS BLUE & LUNCH BAG SPACEBOY DESIGN     0.024318
LUNCH BAG CARS BLUE & LUNCH BAG PINK POLKADOT       0.026252
ALARM CLOCK BAKELIKE RED  & ALARM CLOCK BAKELIK...  0.026598
LUNCH BAG SPACEBOY DESIGN  & LUNCH BAG PINK POL...  0.022453

[228 rows x 1 columns]

In [13]:
df_4 = pd.DataFrame(b.items())
df_4.rename(columns={0:'itemsets', 1:'support'}, inplace=True)
df_4['itemsets'] = df_4['itemsets'].str.split(' & ')
df_4['itemsets'] = df_4['itemsets'].map(frozenset)
# display(df_4)

In [14]:
df_5 = association_rules(df_4, metric='confidence')
display(df_5)

df_6 = association_rules(df_4, metric='lift', min_threshold=1)
display(df_6.nlargest(5, columns='lift'))

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.029845,0.037237,0.024249,0.8125,21.819921,0.023137,5.134738,0.983523

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
34,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.037237,0.029845,0.024249,0.651206,21.819921,0.023137,2.781456,0.991075
35,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.029845,0.037237,0.024249,0.812500,21.819921,0.023137,5.134738,0.983523
12,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.029845,0.040484,0.022522,0.754630,18.640382,0.021313,3.910482,0.975465
13,(ROSES REGENCY TEACUP AND SAUCER ),(PINK REGENCY TEACUP AND SAUCER),0.040484,0.029845,0.022522,0.556314,18.640382,0.021313,2.186581,0.986281
10,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.037237,0.040484,0.027979,0.751391,18.560395,0.026472,3.859547,0.982715

<p style="background-image: linear-gradient(to right, #0aa98f, #68dab2)"> &nbsp; </p>