In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('data/spotify-2023.csv', encoding='latin-1')
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Drop unnecessary columns (for me)

In [4]:
single1 = df[['in_spotify_playlists']]
single2 = df[['in_spotify_charts']]
range1 = df.loc[:,'in_apple_playlists':'in_shazam_charts']
filt = single1 + single2 + range1
# df.drop(columns=filt.columns)    # Always check first
df.drop(columns=filt.columns, inplace=True) 
df.tail()    # Just for see another range of data

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
948,My Mind & Me,Selena Gomez,1,2022,11,3,91473363,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,121871870,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,73513683,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,133895612,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,96007391,90,E,Minor,61,32,67,15,0,11,5

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Create date column and drop old ones

In [5]:
temp_df = pd.DataFrame()
temp_df['year'] = df['released_year'].astype(str)
temp_df['month'] = df ['released_month'].astype(str).str.zfill(2)
temp_df['day'] = df['released_day'].astype(str).str.zfill(2)

df['released_date'] = pd.to_datetime(temp_df[['year', 'month', 'day']])
del(temp_df)
filt = df.loc[:,'released_year':'released_day']
# df.drop(columns=filt.columns)   # Always check first
df.drop(columns=filt.columns, inplace=True)
df.head()

,track_name,artist(s)_name,artist_count,streams,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,released_date
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,141381703,125,B,Major,80,89,83,31,0,8,4,2023-07-14
1,LALA,Myke Towers,1,133716286,92,C#,Major,71,61,74,7,0,10,4,2023-03-23
2,vampire,Olivia Rodrigo,1,140003974,138,F,Major,51,32,53,17,0,31,6,2023-06-30
3,Cruel Summer,Taylor Swift,1,800840817,170,A,Major,55,58,72,11,0,11,15,2019-08-23
4,WHERE SHE GOES,Bad Bunny,1,303236322,144,A,Minor,65,23,80,14,63,11,6,2023-05-18

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Change names of columns | del '_%' if exist

In [6]:
# df.columns
for col in df.columns:
    if '_%' in col:
        new = col[:-2]
        df.rename(columns={col:new}, inplace=True)
df.head()

,track_name,artist(s)_name,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,141381703,125,B,Major,80,89,83,31,0,8,4,2023-07-14
1,LALA,Myke Towers,1,133716286,92,C#,Major,71,61,74,7,0,10,4,2023-03-23
2,vampire,Olivia Rodrigo,1,140003974,138,F,Major,51,32,53,17,0,31,6,2023-06-30
3,Cruel Summer,Taylor Swift,1,800840817,170,A,Major,55,58,72,11,0,11,15,2019-08-23
4,WHERE SHE GOES,Bad Bunny,1,303236322,144,A,Minor,65,23,80,14,63,11,6,2023-05-18

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Separate artist(s)_name column and drop it

In [7]:
temp_df = pd.DataFrame()
temp_df = df['artist(s)_name'].str.split(', ', expand=True)
feat_df = pd.DataFrame(temp_df.iloc[:,1:])

df['artist'] = temp_df[[0]]
df['featuring_artists'] = feat_df.iloc[:,0:7].apply(lambda x: ', '.join(filter(None, x)), axis=1)
df['featuring_artists'].replace({pd.NA: None, None:None, '': None}, inplace=True)
df.drop(columns='artist(s)_name', inplace=True)
del(temp_df, feat_df)
df.tail()

,track_name,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date,artist,featuring_artists
948,My Mind & Me,1,91473363,144,A,Major,60,24,39,57,0,8,3,2022-11-03,Selena Gomez,None
949,Bigger Than The Whole Sky,1,121871870,166,F#,Major,42,7,24,83,1,12,6,2022-10-21,Taylor Swift,None
950,A Veces (feat. Feid),2,73513683,92,C#,Major,80,81,67,4,0,8,6,2022-11-03,Feid,Paulo Londra
951,En La De Ella,3,133895612,97,C#,Major,82,67,77,8,0,12,5,2022-10-20,Feid,"Sech, Jhayco"
952,Alone,1,96007391,90,E,Minor,61,32,67,15,0,11,5,2022-11-04,Burna Boy,None

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Arrange columns order

In [8]:
new_order =['track_name', 'artist', 'featuring_artists','artist_count', 'streams', 'bpm',
            'key', 'mode', 'danceability', 'valence', 'energy', 'acousticness',
            'instrumentalness', 'liveness', 'speechiness', 'released_date']
df = df.loc[:,new_order]
df.head(3)

,track_name,artist,featuring_artists,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date
0,Seven (feat. Latto) (Explicit Ver.),Latto,Jung Kook,2,141381703,125,B,Major,80,89,83,31,0,8,4,2023-07-14
1,LALA,Myke Towers,None,1,133716286,92,C#,Major,71,61,74,7,0,10,4,2023-03-23
2,vampire,Olivia Rodrigo,None,1,140003974,138,F,Major,51,32,53,17,0,31,6,2023-06-30

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Change dtypes of 'streams' column

In [9]:
df['streams'].info()
# df['streams'] = df['streams'].astype(int)    # ERROR

<class 'pandas.core.series.Series'>
RangeIndex: 953 entries, 0 to 952
Series name: streams
Non-Null Count  Dtype
--------------  -----
953 non-null    object
dtypes: object(1)
memory usage: 7.6+ KB

**Fixing streams column**<br>
    → find non-numeric value

In [10]:
df['streams'].max()
# real value on Spotify → 224.800.316

'BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3'

In [11]:
filt = df['streams'] == df['streams'].max()
# df[filt]['streams'] = '224800316'    # ERROR
df.loc[filt, 'streams'] = '224800316'
df[filt]

,track_name,artist,featuring_artists,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,None,1,224800316,110,A,Major,53,75,69,7,0,17,3,1970-01-01

**Now ready to change**

In [12]:
display(df['streams'].dtypes)
df['streams'] = df['streams'].astype(int)
display(df['streams'].dtypes)

dtype('O')

dtype('int64')

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

**Fix some values**<br>
    → min streams values (first two) are too small for this dataset
    → find min value (2 times)

In [13]:
df.sort_values(by='streams').head()    # first see min values
# real value on Spotify -> 557.890.134 and 179.111.799

,track_name,artist,featuring_artists,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date
123,Que Vuelvas,Carin Leon,Grupo Frontera,2,2762,162,A#,Major,49,78,64,19,0,11,4,2022-12-09
393,Jhoome Jo Pathaan,Arijit Singh,"Vishal Dadlani, Sukriti Kakar, Vishal-Shekhar,...",6,1365184,105,G,Major,82,62,74,10,0,33,7,2022-12-22
144,QUEMA,Sog,"Ryan Castro, Peso Pluma",3,11599388,97,NaN,Major,79,92,89,5,0,6,5,2023-07-13
142,"Gol Bolinha, Gol Quadrado 2",Mc Pedrinho,DJ 900,2,11956641,133,B,Minor,93,68,65,42,0,12,25,2023-06-01
68,Overdrive,Post Malone,None,1,14780425,140,C#,Major,56,48,73,0,0,35,4,2023-07-14

In [14]:
correct_values = [557890134, 179111799]    # order is important first the minimum than one bigger from data
for value in correct_values:
    filt = df['streams'] == df['streams'].min()
    df.loc[filt, 'streams'] = value

df.iloc[[123, 393],]    # see new values

,track_name,artist,featuring_artists,artist_count,streams,bpm,key,mode,danceability,valence,energy,acousticness,instrumentalness,liveness,speechiness,released_date
123,Que Vuelvas,Carin Leon,Grupo Frontera,2,557890134,162,A#,Major,49,78,64,19,0,11,4,2022-12-09
393,Jhoome Jo Pathaan,Arijit Singh,"Vishal Dadlani, Sukriti Kakar, Vishal-Shekhar,...",6,179111799,105,G,Major,82,62,74,10,0,33,7,2022-12-22

In [15]:
# df.sort_values(by='streams')
# df.sort_values(by='streams', ascending=False)
# df.sort_values(by='streams', ascending=False, inplace=True)

<p style="background-image: linear-gradient(#0D9276, #FFFFFF 10%)"> &nbsp </p>

#### Write data to new csv

In [16]:
# df.to_csv('data/spotify_2023_clean.csv', index=False)